bundleid: net.turbare.switch-vpn
category: Tools
connections:
  select_vpn:
  - destinationuid: switch_vpn
  switch_vpn: []
createdby: Akihiro Uchida
description: switch VPN connection
disabled: false
name: alfred-switch-vpn
objects:
- config:
    applescript: !include 'switch_vpn'
  type: alfred.workflow.action.applescript
  uid: switch_vpn
- config:
    argumenttype: 1
    keyword: vpn
    runningsubtext: Finding VPN devices
    script: !include 'select_vpn'
    subtext: Start typing a VPN service name...
    title: switch a VPN service
  type: alfred.workflow.input.scriptfilter
  uid: select_vpn
readme: !include 'README'
uidata:
  select_vpn:
    ypos: 30
  switch_vpn:
    ypos: 30
webaddress: github.com/uchida/alfred-switch-vpn
